# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Boomerang.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: yarn
    - run: yarn lint
    - run: yarn build
    - run: yarn test

  slack:
    name: Send Slack Notification
    if: always()

    runs-on: ubuntu-latest

    needs: 
    - build

    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      BUILD_COLOR: ${{ fromJSON('["red#d32f2f", "green#4caf50" ]')[ contains(fromJSON('["${{ needs.build.result }}", "warning"]'), 'failed') ] }}
      BUILD_STATUS: ${{ fromJSON('["failed", "passed" ]')[ '${{ needs.build.result }}' == 'success' ] }}
      REPOSITORY_ACTION_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
      REPOSITORY_LATEST_COMMIT_URL: https://github.com/${{ github.repository }}/commit/${{ github.sha }}

    steps:
    - name: Sending notification
      uses: slackapi/slack-github-action@v1.15.0
      with:
        payload: '{"text": "Repo `${{ github.repository }}` *${{ env.BUILD_STATUS }}`${{ env.BUILD_COLOR }}`* build (<${{ env.REPOSITORY_ACTION_URL }}|#${{ github.run_id }}>) for commit (<${{ env.REPOSITORY_LATEST_COMMIT_URL }}|${{ github.sha }}>) on branch `${{ github.ref }}`"}'
