# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Boomerang.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: yarn
    - run: yarn lint
    - run: yarn build
    - run: yarn test
    
  notify:
    runs-on: ubuntu-latest
    
    needs: 
    - build

    env:
      SLACK_COLOR: "#c3e6cb"

    steps:
    - uses: slackapi/slack-github-action@v1.14.0
      with:
        attachments: 
          color: ${{ env.SLACK_COLOR }}
          blocks: 
            type: "section"
            text:
              type: 'mrkdwn'
              text: "Repo `${{ github.repository }}` *${{ job.status }}* build () for commit () on branch `branch`"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
